### PR TITLE
contrib/7zip: new package

### PR DESCRIPTION
**Pull request by nekopsykose**
very spicy, get a cucumber soda first

### CODE REVIEW

**Comment by q66** [comment]
y tho

**Comment by nekopsykose** [comment]
why not, it's the reference tool for working with 7z archives

libarchive can read/write them fine too, but it is missing features (most notably, the aes256 encryption support entirely)

or do you mean why get a cucumber soda? is tasty

**Comment by nekopsykose** [comment]
example:  

```console
$ 7z a -pROFL lol.7z ~/src/cports/CONTRIBUTING.md 
[...]]
Everything is Ok
$ 7z x lol.7z                                    
[...]
Enter password:
$ tar xf lol.7z
CONTRIBUTING.md: The file content is encrypted, but currently not supported: No such file or directory
tar: Error exit delayed from previous errors.
```

**Comment by q66** [comment]
in any case this cannot be merged as is considering it for most part completely ignores the distro cflags

**Comment by nekopsykose** [comment]
just cxxflags were missing, should be ok

**Pull request merged**
