### PR TITLE
contrib/nc: new package (3.8.2)

### PR DESCRIPTION
**Pull request by subnut**

### CODE REVIEW

**Comment by subnut** [comment]
netcat has a much simpler syntax than socat, and IMHO seems to be more popular than socat/ncat/etc.

Also, among netcat/gnu-netcat/openbsd-netcat, the openbsd one seems to be more popular IMHO.

I can't provide numbers, but that's the general trend I've seen in reddit/stackoverflow/etc.

**Comment by subnut** [comment]
And libressl's nc is pretty much directly copied from the OpenBSD `src` tree (AFAIR)

**Comment by subnut** [comment]
I did it this way instead of just packaging the whole libressl because... well we already have OpenSSL. And I presume q99 won't like the idea of having _both_ libressl _and_ openssl

**Comment by q66** [comment]
the template doesn't meet packaging quality requirements, and i'm not interested in a hacky build like this anyway

it's also not guaranteed to work because the libretls ABI may not match the libressl ABI, so it's just overall a bad idea

i wouldn't be opposed to importing the freebsd variant of netcat in chimerautils, but definitely not this

**Comment by nekopsykose** [comment]
> it's also not guaranteed to work because the libretls ABI may not match the libressl ABI, so it's just overall a bad idea  

the libretls abi does match the libtls abi. that's why it exists in the first place

the rest stands tho

**Comment by q66** [comment]
afaict it's not required to, libressl can bump their soname and then it'll no longer match like this

**Comment by nekopsykose** [comment]
yeah, every libressl major the soname goes up, and then one would have to wait for libretls to catch up with the changes. that's because libressl breaks every release

but aside from that they match :)

**Pull request closed without merging**
