### PR TITLE
contrib/*: disable cfi and remove cfi todos for all kde stuff

### PR DESCRIPTION
**Pull request by triallax**
cfi causes a lot of crashes for kde projects, and fixing them just doesn't seem worth it

[ci skip]

### CODE REVIEW

**Comment by nekopsykose** [comment]
vis does do something if the project doesn't already set it (since it will remove some symbols from shared libraries so they end up smaller via pruning symbols that are otherwise just default exported). so since it works might as well leave it for the libraries specifically

**Comment by nekopsykose** [comment]
> if the project doesn't already set it

(but i'm pretty sure almost every kde project does pass it themselves already)

**Comment by triallax** [comment]
@nekopsykose sure, i'll keep this in mind for other packages as well

**Comment by nekopsykose** [comment]
forgor 2 merge this before the plasma bump, just rebase it then merge it

**Pull request merged**
