### PR TITLE
replace eog with loupe

### PR DESCRIPTION
**Pull request by Drsheppard01**

### CODE REVIEW

**Comment by q66** [comment]
nah, i don't think so yet

**Comment by Drsheppard01** [comment]
Not to be intrusive, but instead of the familiar gnome-terminal and gedit, gnome meta comes with their counterparts with less functionality. The gnome meta package also includes gnome-screenshot, but its function was implemented in gnome-shell

**Comment by q66** [comment]
i don't see how any of that is related to this?

**Comment by Drsheppard01** [comment]
Of course I should have asked for a reason why you're not ready to merge it. But if I understand correctly, the reason is a lack of functional parity

**Pull request closed without merging**
