### PR TITLE
contrib/rlwrap: new package (0.46.1)

### PR DESCRIPTION
**Pull request by ttyyls**

### CODE REVIEW

**Comment by q66** [comment]
does this provide anything over just using socat? because this thing is dead

**Comment by wezm** [comment]
Isn't socat a different thing? rlwrap lets you use readline line editing and history features on tools that don't use it.

**Comment by q66** [comment]
`socat READLINE EXEC:<your command line>`

**Comment by ttyyls** [comment]
fair enough

**Pull request closed without merging**
