### PR TITLE
[New package]: diffutils-3.8 [WIP]

### PR DESCRIPTION
**Pull request by ndowens**
Marking WIP as got to test against other possible Archs

### CODE REVIEW

**Comment by q66** [comment]
why?

**Comment by ndowens** [comment]
> why? (also this will create a package that is not installable because of file conflicts)

Hmm ok, it was listed as a dep for autoconf, which has autoreconf and believed we'd need this in repo for packages that uses it?

**Comment by q66** [comment]
```
q66@rimi: /home/q66/cports-orig$ ./cbuild chroot
OK: 376 distinct packages available
# apk info -L bsddiff
bsddiff-0.99.0-r0 contains:
usr/bin/cmp
usr/bin/diff
usr/bin/diff3
usr/bin/sdiff
usr/libexec/diff3prog
usr/share/man/man1/cmp.1
usr/share/man/man1/diff.1
usr/share/man/man1/diff3.1
usr/share/man/man1/sdiff.1

# exit
q66@rimi: /home/q66/cports-orig$ xbps-query -f diffutils
/usr/bin/cmp
/usr/bin/diff
/usr/bin/diff3
/usr/bin/sdiff
/usr/share/info/diffutils.info.gz
/usr/share/locale/bg/LC_MESSAGES/diffutils.mo
/usr/share/locale/ca/LC_MESSAGES/diffutils.mo
/usr/share/locale/cs/LC_MESSAGES/diffutils.mo
/usr/share/locale/da/LC_MESSAGES/diffutils.mo
/usr/share/locale/de/LC_MESSAGES/diffutils.mo
/usr/share/locale/el/LC_MESSAGES/diffutils.mo
/usr/share/locale/eo/LC_MESSAGES/diffutils.mo
/usr/share/locale/es/LC_MESSAGES/diffutils.mo
/usr/share/locale/fi/LC_MESSAGES/diffutils.mo
/usr/share/locale/fr/LC_MESSAGES/diffutils.mo
/usr/share/locale/ga/LC_MESSAGES/diffutils.mo
/usr/share/locale/gl/LC_MESSAGES/diffutils.mo
/usr/share/locale/he/LC_MESSAGES/diffutils.mo
/usr/share/locale/hr/LC_MESSAGES/diffutils.mo
/usr/share/locale/hu/LC_MESSAGES/diffutils.mo
/usr/share/locale/id/LC_MESSAGES/diffutils.mo
/usr/share/locale/it/LC_MESSAGES/diffutils.mo
/usr/share/locale/ja/LC_MESSAGES/diffutils.mo
/usr/share/locale/lv/LC_MESSAGES/diffutils.mo
/usr/share/locale/ms/LC_MESSAGES/diffutils.mo
/usr/share/locale/nb/LC_MESSAGES/diffutils.mo
/usr/share/locale/nl/LC_MESSAGES/diffutils.mo
/usr/share/locale/pl/LC_MESSAGES/diffutils.mo
/usr/share/locale/pt/LC_MESSAGES/diffutils.mo
/usr/share/locale/pt_BR/LC_MESSAGES/diffutils.mo
/usr/share/locale/ro/LC_MESSAGES/diffutils.mo
/usr/share/locale/ru/LC_MESSAGES/diffutils.mo
/usr/share/locale/sr/LC_MESSAGES/diffutils.mo
/usr/share/locale/sv/LC_MESSAGES/diffutils.mo
/usr/share/locale/tr/LC_MESSAGES/diffutils.mo
/usr/share/locale/uk/LC_MESSAGES/diffutils.mo
/usr/share/locale/vi/LC_MESSAGES/diffutils.mo
/usr/share/locale/zh_CN/LC_MESSAGES/diffutils.mo
/usr/share/locale/zh_TW/LC_MESSAGES/diffutils.mo
/usr/share/man/man1/cmp.1
/usr/share/man/man1/diff.1
/usr/share/man/man1/diff3.1
/usr/share/man/man1/sdiff.1
```

**Comment by ndowens** [comment]
Ah I see, closing

**Comment by q66** [comment]
(okay, i guess it does pass tests; i was under the impression that perl is needed for the test suite, but apparently is not)

in any case, there is no need for diffutils unless the GNU versions provide something that is needed by another package, and i don't think they do

in case there is something, it would have to be packaged with proper `--program-prefix=g` in order to not conflict (and it would likely go in `contrib/`)

**Comment by ndowens** [comment]
Gotcha, thanks for the wasted time :) Going to work on autoconf as we will probably need that, as I am working on libxcrypt which seems to need libucontext package to link against since it is musl and not glibc.

**Comment by q66** [comment]
why? libucontext is built with meson or a makefile

**Comment by ndowens** [comment]
> why? libucontext is built with meson or a makefile

autoreconf for libxcrypt as adding a patch to link against libucontext ifndef __GLIBC__

**Comment by q66** [comment]
you can patch the generated files instead of the original files, then you don't need to autoreconf

what is libxcrypt needed for?

**Comment by ndowens** [comment]
IIRC I was trying to start process of adding dropbear, to atleast have one ssh server available and less deps needed. If you think it'd be worth while adding? Atleast adding autoconf will be useful for later, dropbear can wait or not be added, your choice. Trying to contribute a bit :)

**Comment by q66** [comment]
dropbear just uses the `crypt()` API, which is already provided by `musl` (`glibc` too, but it's removing it: https://fedoraproject.org/wiki/Changes/Replace_glibc_libcrypt_with_libxcrypt)

**Comment by ndowens** [comment]
> dropbear just uses the `crypt()` API, which is already provided by `musl` (`glibc` too, but it's removing it: https://fedoraproject.org/wiki/Changes/Replace_glibc_libcrypt_with_libxcrypt)

Ah gotcha, ok will skip libxcrypt in that case

**Comment by q66** [comment]
that said, the ssh server in `main` is going to be openssh (there is no problem with packaging dropbear though, it can go probably in `contrib` if there aren't any issues with it)

**Pull request closed without merging**
