### PR TITLE
contrib/power-profiles-daemon: new package (0.13)

### PR DESCRIPTION
**Pull request by valpackett**
this thingy:

gnome quick settings for power profile

### CODE REVIEW

**Comment by q66** [comment]
the git repo says it's archived, do you know what's the deal with that?

**Comment by nekopsykose** [comment]
the maintainer got let go by redhat: https://www.hadess.net/2023/08/new-responsibilities.html?m=1  

that aside, still works afaik, i'd assume someone would carry it in some form for this piece of functionality to stay working if needed, eventually

**Comment by q66** [comment]
i see

template otherwise looks good, needs lint fixing and update-check needs fixing

**Comment by valpackett** [comment]
Interesting, update-check doesn't seem to fail for me locally :eyes: 

```
=> power-profiles-daemon-0.13-r0: running init_fetch hook: 000_env_pkg_config...
=> power-profiles-daemon-0.13-r0: running pre_fetch hook: 000_update_check...
=> power-profiles-daemon-0.13-r0: running do_fetch hook: 000_sources...
=> cbuild: updating software in /home/val/src/github.com/chimera-linux/cports/bldroot container...
```

**Comment by valpackett** [comment]
So that was a transient failure related to gitlab.fdo (?)

**Comment by q66** [comment]
yeah seems that way, it's been having connectivity issues for quite a while now

**Pull request merged**
