### PR TITLE
user/nextcloud-desktop: new package

### PR DESCRIPTION
**Pull request by doskel**
## Description

Added nextcloud-desktop package to provide desktop sync for the Nextcloud cloud system. This was mostly lifted from #2865 and updated to use the newer package versions.

## Checklist

Before this pull request is reviewed, certain conditions must be met.

The following must be true for all changes:

- [ ] I have read [CONTRIBUTING.md](https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md)

The following must be true for template/package changes:

- [x] I have read [Packaging.md](https://github.com/chimera-linux/cports/blob/master/Packaging.md#quality_requirements)
- [x] I have built and tested my changes on my machine

### CODE REVIEW

**Comment by q66** [comment]
https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md#committing-changes

**Comment by doskel** [comment]
> https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md#committing-changes

Resolved. Apologies for missing it.

**Comment by q66** [comment]
the title of the pull request doesn't matter, the commit does

**Comment by doskel** [comment]
i've no clue what i'm doing atm. i'm going to go actually learn git and the like, and then hopefully come back later with a competent PR lol

**Comment by JamiKettunen** [comment]
there's no need to close this PR, you may re-open this and force-push once you've fixed things on your local branch after looking over [USING_GIT.md](https://github.com/chimera-linux/cports/blob/master/USING_GIT.md) which already was linked from [CONTRIBUTING.md](https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md)

**Comment by q66** [comment]
i just fixed it up for you, you can try again with some other one later

**Pull request closed without merging**
