### PR TITLE
main/libblockdev: enable nvdimm support

### PR DESCRIPTION
**Pull request by nekopsykose**

### CODE REVIEW

**Comment by q66** [comment]
all moves need revbump or the builders won't pick it up properly

**Comment by nekopsykose** [comment]
i could roll volume_key into here too if you want it

**Comment by q66** [comment]
remind me, what does volume_key involve?

**Comment by nekopsykose** [comment]
whatever https://manpages.ubuntu.com/manpages/focal/en/man8/volume_key.8.html talks about but just to allow creating an escrow in libblockdev http://storaged.org/libblockdev/libblockdev-Crypto.html#bd-crypto-escrow-device. i guess that's a pretty small feature

for packaging volume_key itself look at https://github.com/alpinelinux/aports/blob/fd4c98b8edd944f9866b48751a05243dbd77b404/community/volume_key/APKBUILD i guess

**Comment by q66** [comment]
looks small enough, let's roll that in

**Comment by nekopsykose** [comment]
hrm not sure how well that works, the last release is 5 years ago, the tests crash in  

```
  gpgme_res = gpgme_data_release_and_get_mem (dest_data, res_size);
  if (gpgme_res == NULL)
    {
      g_set_error (error, LIBVK_ERROR, LIBVK_ERROR_CRYPTO,
		   _("Unknown error getting encryption result"));
      goto err_ctx;
    }
```
(maybe a gpgme issue), the python bindings don't even build due to some libtool rpath thing, ..

**Comment by q66** [comment]
let's not bother for now then

**Comment by nekopsykose** [comment]
aye aye

also patched the version script instead of --no-undefined

**Pull request merged**
