### PR TITLE
New packages

### PR DESCRIPTION
**Pull request by wezm**
Wasn't sure whether to raise these as individual PRs or not, can do if desired.

I created these packages as part of packaging the Awesome window manager (I'll raise that separately when I've done a bit more testing on it). You may be wondering why ImageMagick is included. It turns out that as part of the Awesome build process they process some icons with `convert`.

### CODE REVIEW

**Comment by q66** [comment]
I don't really plan to add more contrib/ packages that are not necessary for a specific development purpose right now, as it means more stuff to deal with when refactoring

feel free to keep it open (probably convert to draft for now, but up to you), feel free to add more to it if you like, but it'll have to wait until apk3 transition has finished and cports has been declared safe

**Comment by q66** [comment]
also none of these packages should go to main/

**Comment by wezm** [comment]
> I don't really plan to add more contrib/ packages that are not necessary for a specific development purpose right now, as it means more stuff to deal with when refactoring

No worries. 

> also none of these packages should go to main/

Cool, wasn't sure about that.

**Comment by q66** [comment]
if you feel like rebasing and cleaning these up, feel free to do so, i'll review it afterwards

**Comment by wezm** [comment]
Ok I’ll see if I can get them updated in the coming week

**Comment by wezm** [comment]
Thanks for committing these. Have been too busy with other stuff to do the update myself.

**Pull request closed without merging**
