### PR TITLE
contrib/neovim: new package (0.9.0)

### PR DESCRIPTION
**Pull request by yopito**
build and usage fine on ` x86_64`, even within `cbuild chroot` environnement.  
crossbuild need some investigations.

### CODE REVIEW

**Comment by q66** [comment]
something i noticed in all your stuff, you're separating things like options from the main block while you shouldn't

**Comment by yopito** [comment]
OK, i'll fix that

**Comment by q66** [comment]
also there's a lot of pointless comments scattered all over the place and we should probably build neovim against standard lua because luajit is a mess

**Comment by yopito** [comment]
> also there's a lot of pointless comments scattered all over the place and we should probably build neovim against standard lua because luajit is a mess

I missed that neovim can live without luajit, have to review and test.

**Comment by yopito** [comment]
reworked to remove luaJIT usage. ready for review

**Comment by yopito** [comment]
ah, bad commit message. quick git push within a minute, sorry

**Comment by q66** [comment]
can you please squash the update commits, update where appropriate and so on? basically do whatever you may think is necessary for merging, so i can review it

**Comment by yopito** [comment]
here it is. thanks for rewieving

**Comment by q66** [comment]
alright thanks, i'll probably merge it by pieces (i'll do adjustments to the templates as i think is necessary, probably faster than having you iterate on it; and it's a fair amount of commits)

**Pull request closed without merging**
