### PR TITLE
main/samba: update to 4.18.6

### PR DESCRIPTION
**Pull request by nekopsykose**

### CODE REVIEW

**Comment by q66** [comment]
4.19.0 is out (probably also gonna need an ldb update)

**Comment by nekopsykose** [comment]
the whole build is effectively -j1 looking at it, i'd guess WAF_MAKE=1 is kinda scuffed

**Comment by nekopsykose** [comment]
could also add `vfs_io_uring` to shared-modules with liburing moved to main

**Comment by q66** [comment]
it's pretty useless and i don't really want to move it right now

**Pull request merged**
