### PR TITLE
Package xfce4 panel plugins

### PR DESCRIPTION
**Pull request by triallax**

### CODE REVIEW

**Comment by nekopsykose** [comment]
these don't take very long to build so you can drop the [ci skip] too once you clean it up

**Comment by triallax** [comment]
yeah, i just added it for now because i know that sensors build is broken and i haven't fixed it yet

**Comment by triallax** [comment]
i've been told by upstream that the list of panel plugins in https://docs.xfce.org/ is the semi-official list of plugins that i should probably package; i packaged most of them except for these:
- datetime: archived
- embed: last release in 2015
- mount: needs glibc's fstab.h thing
- mpc: dead libmpd dependency
- statusnotifier: "As of xfce 4.15, the functionality provided by xfce4-statusnotifier-plugin has been integrated into the xfce4-panel's systray. Going forward, this plugin is considered to be deprecated. "
- sample: well, sample plugin
- weather: still on libsoup2, draft pr (with merge conflicts) exists https://gitlab.xfce.org/panel-plugins/xfce4-weather-plugin/-/merge_requests/28

**Comment by nekopsykose** [comment]
sounds good

**Pull request merged**
