### PR TITLE
main/fortify-headers: update to 2.3.1

### PR DESCRIPTION
**Pull request by nekopsykose**
overlap checks got some fixes, mem* null checks are now off by default without a pedantic define set

### CODE REVIEW

**Comment by nekopsykose** [comment]
also might want to use the USE_NATIVE_CHK? they might be a bit worse but if they improve diagnostics (should test) it would be nice, because the current diagnostics are quite bad

**Comment by nekopsykose** [comment]
some quick stuff (and openssl) still seems to pass tests so i guess it's fine. the only changes are vasprintf/asprintf being added and the reenablement of the overlap checks

**Comment by nekopsykose** [comment]
nvm, the native chk requires libc support

**Comment by q66** [comment]
we should probably disable the printf stuff for now too https://github.com/jvoisin/fortify-headers/issues/62

**Comment by nekopsykose** [comment]
seems even more issues showed up :D  

will just wait for next release

**Comment by nekopsykose** [comment]
seems those are disabled on clang anyway so, no real changes

**Pull request merged**
