### PR TITLE
contrib/copyq: update to 8.0.0

### PR DESCRIPTION
**Pull request by ttyyls**
this update also drops X11 support alongside its build dependencies, and turn off notifications support explicitely (previously implicitelt disabled) since it relies on knotifications.

### CODE REVIEW

**Comment by nekopsykose** [comment]
> this updated also drops X11 support  

why?

**Comment by ttyyls** [comment]
> > this updated also drops X11 support
> 
> why?

no particular reason, the option just landed in this update https://github.com/hluk/CopyQ/releases/tag/v8.0.0 and I thought of taking advantage of it to lighten the build.

**Comment by nekopsykose** [comment]
> no particular reason,  

then don't

**Comment by nekopsykose** [comment]
(we don't disable it anywhere else globally either, the only thing i can think of similarly is not adding alsa to things where pulse/pipewire exists)

**Comment by ttyyls** [comment]
reverted

**Pull request merged**
