### PR TITLE
main/ansible: update to 10.4.0

### PR DESCRIPTION
**Pull request by tulilirockz**

### CODE REVIEW

**Comment by nekopsykose** [comment]
this is released in sync with ansible-core which you didn't update here (i'll do it instead). also how do you test this?

**Comment by tulilirockz** [comment]
oh :p i just built it, it seemed fine, so i made the PR... will not do that again ever since thats super dumb.

**Comment by tulilirockz** [comment]
(the other ones are tested tho)

**Comment by nekopsykose** [comment]
haha, sure

**Comment by tulilirockz** [comment]
ya got me. (sorry tho for real, this is just bad practice i shouldnt do that)

**Pull request merged**
