### PR TITLE
main/bubblewrap: restore all tests

### PR DESCRIPTION
**Pull request by yoctozepto**
No version bump as the pkg does not change.

### CODE REVIEW

**Comment by yoctozepto** [comment]
On these notes:

1) The portability patch could be upstreamed by omitting the disablement of seccomp test.
2) I could not get the python binding for seccomp to work. If anyone wants to pick this effort up, the binding is part of libseccomp itself, enabled by the `--enable-python` switch after having installed `python-cython` and `python-devel`. I believe I lack cython and/or legacy packaging experience to fix the resulting build.

**Comment by yoctozepto** [comment]
cc @q66

**Comment by nekopsykose** [comment]
> The only test remaining disabled is the one for seccomp because
chimera lacks python bindings for libseccomp.

added

**Comment by yoctozepto** [comment]
Oh, lovely, @nekopsykose! TYVM

Let me try it.

**Comment by yoctozepto** [comment]
It works!

**Pull request merged**
