### PR TITLE
Monolith

### PR DESCRIPTION
**Pull request by sudanchapagain**
## Description

new package

Describe what your pull request does here. For new packages, this is the
purpose of the package, for other changes this is what your change does,
for trivial package updates you may remove this.

## Checklist

Before this pull request is reviewed, certain conditions must be met.

The following must be true for all changes:

- [x] I have read [CONTRIBUTING.md](https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md)

The following must be true for template/package changes:

- [x] I have read [Packaging.md](https://github.com/chimera-linux/cports/blob/master/Packaging.md#quality_requirements)
- [x] I have built and tested my changes on my machine

### CODE REVIEW

**Comment by JamiKettunen** [comment]
why did you close this? you could've just force-pushed to this branch to fix mistakes like inclusion of `user/love` and not make a new PR but now you have to since you deleted the branch and thus github no longer allows you to re-open this one

**Comment by sudanchapagain** [comment]
i thought i screwed up.

**Comment by JamiKettunen** [comment]
[USING_GIT.md](https://github.com/chimera-linux/cports/blob/master/USING_GIT.md) linked from [CONTRIBUTING.md](https://github.com/chimera-linux/cports/blob/master/CONTRIBUTING.md) explains how you could've fixed it

**Comment by sudanchapagain** [comment]
i rebase monolith branch and made a new pr, i hope it works fine.

**Pull request closed without merging**
