### PR TITLE
contrib/localectl: new package (1.0.0)

### PR DESCRIPTION
**Pull request by Gnarwhal**
Hopefully it is in the realm of what you were looking for

Here is the source url: https://github.com/Gnarwhal/localectl-chimera

### CODE REVIEW

**Comment by q66** [comment]
as i previously mentioned this should be a part of openrc-settingsd and not a separate project

**Comment by Gnarwhal** [comment]
Oh you sure did. I'm so sorry I misinterpreted that. Sorry another probably base question then, but are you saying you would fork https://gitlab.com/postmarketOS/openrc-settingsd/-/tree/main/src?ref_type=heads and add localectl to it?

**Comment by q66** [comment]
yes, and ideally upstream it, but that can come later (let's fork it downstream first and i'll review the code)

**Comment by Gnarwhal** [comment]
Ok I believe I've got it working.
https://gitlab.com/Gnaaarwhal/openrc-settingsd/

**Comment by q66** [comment]
thanks, i'll review it this weekend

**Comment by q66** [comment]
sorry for taking ages, i went through the source this evening and cleaned a lot of it up; i kept your commit authorship and added myself as co-authored

i'd like to get this upstreamed so we should coordinate this somehow

**Comment by Gnarwhal** [comment]
No worries at all :)
Thank you for taking the time to review <3

Getting it upstreamed would be nice, but I'll be the first to admit I don't know what that process looks like.

**Pull request closed without merging**
