### PR TITLE
main/eventlog: drop

### PR DESCRIPTION
**Pull request by triallax**
i could also probably make syslog-ng link against system eventlog, but idk

### CODE REVIEW

**Comment by nekopsykose** [comment]
i think if things link a vendored copy they should at least do it statically. otherwise in the future eventlog might be readded for some reason and then it just conflicts again

so, either make it link system, or make it link the vendored one without installing a /usr/lib/whatever.so

**Comment by q66** [comment]
the vendoring should be fixed, but this technically does not change anything from current status other than dropping the other package so it's fine for now

**Comment by nekopsykose** [comment]
sure, we can forget about it forever and not fix it

**Comment by q66** [comment]
there

**Comment by nekopsykose** [comment]
ty vm

**Pull request merged**
