### PR TITLE
main/networkmanager: update to 1.44.2

### PR DESCRIPTION
**Pull request by nekopsykose**
https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/57834169d87791cb3253a24d2c771ba0c4b5f41a/NEWS

### CODE REVIEW

**Comment by nekopsykose** [comment]
vapigen has a legit crash here it seems

```
root@cbuild: /builddir/networkmanager-1.44.2/build$ /usr/bin/vapigen --library=libnm --directory=/builddir/networkmanager-1.44.2/build/vapi --pkg=gio-2.0 --metadatadir=/builddir/networkmanager-1.44.2/vapi /builddir/networkmanager-1.44.2/build/src/libnm-client-impl/NM-1.0.gir
Segmentation fault (core dumped)
```

**Comment by nekopsykose** [comment]
```
(lldb) bt
* thread #1, name = 'vapigen', stop reason = signal SIGSEGV
  * frame #0: 0x00007fc2552ae140 ld-musl-x86_64.so.1`strlen(s=<unavailable>) at strlen.c:17:29
    frame #1: 0x00007fc254b71cc9 libvala-0.56.so.0`___lldb_unnamed_symbol3727 + 201
    frame #2: 0x00007fc254b71698 libvala-0.56.so.0`vala_markup_reader_read_token + 680
    frame #3: 0x00007fc254b0fbab libvala-0.56.so.0`___lldb_unnamed_symbol3438 + 299
    frame #4: 0x00007fc254b13b44 libvala-0.56.so.0`___lldb_unnamed_symbol3450 + 1028
    frame #5: 0x00007fc254b07f1c libvala-0.56.so.0`___lldb_unnamed_symbol3386 + 16188
    frame #6: 0x00007fc254b031a8 libvala-0.56.so.0`vala_gir_parser_parse_file + 1384
    frame #7: 0x00007fc254aab8ad libvala-0.56.so.0`vala_code_context_accept + 221
    frame #8: 0x00007fc254af98fe libvala-0.56.so.0`vala_gir_parser_parse + 2334
    frame #9: 0x00005585f4cdeec3 vapigen`___lldb_unnamed_symbol701 + 2083
    frame #10: 0x00007fc25525824a ld-musl-x86_64.so.1`libc_start_main_stage2(main=(vapigen`___lldb_unnamed_symbol701), argc=<unavailable>, argv=0x00007fffd783cda8) at __libc_start_main.c:95:7
```

**Comment by q66** [comment]
this is useless without the debug symbols

**Comment by q66** [comment]
better backtrace

```
* thread #1, name = 'vapigen', stop reason = signal SIGSEGV
  * frame #0: 0x00007ff2616ae140 ld-musl-x86_64.so.1`strlen(s=<unavailable>) at strlen.c:17:29
    frame #1: 0x00007ff261171cc9 libvala-0.56.so.0`vala_markup_reader_text(self=0x00007ff260601c80, end_char='<', rm_trailing_whitespace=1) at valamarkupreader.c:996:9
    frame #2: 0x00007ff261171698 libvala-0.56.so.0`vala_markup_reader_read_token(self=0x00007ff260601c80, token_begin=0x00007fffde7831e0, token_end=0x00007fffde7831d0) at valamarkupreader.c:899:16
    frame #3: 0x00007ff26110fbab libvala-0.56.so.0`vala_gir_parser_parse_symbol_doc [inlined] vala_gir_parser_next(self=0x00007ff25f4bebe0) at valagirparser.c:1486:11
    frame #4: 0x00007ff26110fb8e libvala-0.56.so.0`vala_gir_parser_parse_symbol_doc(self=0x00007ff25f4bebe0) at valagirparser.c:5218:4
    frame #5: 0x00007ff261113b44 libvala-0.56.so.0`vala_gir_parser_parse_function(self=0x00007ff25f4bebe0, element_name="") at valagirparser.c:8288:12
    frame #6: 0x00007ff261107f1c libvala-0.56.so.0`vala_gir_parser_parse_namespace at valagirparser.c:0
    frame #7: 0x00007ff261107a49 libvala-0.56.so.0`vala_gir_parser_parse_namespace(self=0x00007ff25f4bebe0) at valagirparser.c:4907:11
    frame #8: 0x00007ff2611031a8 libvala-0.56.so.0`vala_gir_parser_parse_file at valagirparser.c:3682:4
    frame #9: 0x00007ff26110306b libvala-0.56.so.0`vala_gir_parser_parse_file(self=0x00007ff25f4bebe0, source_file=<unavailable>) at valagirparser.c:1466:2
    frame #10: 0x00007ff2610ab8ad libvala-0.56.so.0`vala_code_context_accept [inlined] vala_code_visitor_visit_source_file(self=0x00007ff25f4bebe0, source_file=0x00007ff260402f10) at valacodevisitor.c:226:3
    frame #11: 0x00007ff2610ab899 libvala-0.56.so.0`vala_code_context_accept [inlined] vala_source_file_accept(self=0x00007ff260402f10, visitor=0x00007ff25f4bebe0) at valasourcefile.c:837:2
    frame #12: 0x00007ff2610ab899 libvala-0.56.so.0`vala_code_context_accept(self=0x00007ff260e06a90, visitor=0x00007ff25f4bebe0) at valacodecontext.c:2012:3
    frame #13: 0x00007ff2610f98fe libvala-0.56.so.0`vala_gir_parser_parse(self=0x00007ff25f4bebe0, context=0x00007ff260e06a90) at valagirparser.c:1004:2
    frame #14: 0x000055ef5d797ec3 vapigen`___lldb_unnamed_symbol701 + 2083
    frame #15: 0x00007ff26165824a ld-musl-x86_64.so.1`libc_start_main_stage2(main=(vapigen`___lldb_unnamed_symbol701), argc=<unavailable>, argv=0x00007fffde783708) at __libc_start_main.c:95:7
```

it appears to be new to 1.44.2, does not happen with 1.44.0

**Comment by nekopsykose** [comment]
> this is useless without the debug symbols  

i did have them installed fwiw, not sure why sometimes they fail like that, issue for another day

**Pull request closed without merging**
