### PR TITLE
main/harfbuzz: document !cross

### PR DESCRIPTION
**Pull request by z-erica**

### CODE REVIEW

**Comment by q66** [comment]
that doesn't need documenting, all g-i packages are universally uncrossable

**Comment by triallax** [comment]
> dunno, i feel like that fact should be documented somehow (either individually per g-i package like im doing, or somewhere else globally)

Packaging.md would be nice imo

**Comment by q66** [comment]
i mean in the sense of needing a comment in every single thing using gobject-introspection, we definitely don't want that

if you want to drop a note somewhere else go ahead, but putting it in the template makes no sense unless it's also everywhere else and putting it everywhere is kinda meh

**Comment by q66** [comment]
but tbh i'd rather have a mechanism to make this automatic (i.e. gobject-introspection exists in hostdeps, you have implicit !cross)

but i thought about this before and haven't come up with anything good yet

**Pull request closed without merging**
