### PR TITLE
bootstrap.sh: fully support custom BOOTSTRAP_ROOT

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by q66** [comment]
why?

**Comment by yopito** [comment]
This helps to script bootstrap tests, since a not-random BOOTSTRAP_ROOT can be controlled, instead of creating a new one each time.
Since BOOTSTRAP_ROOT already can be reused (once created), this is just a small enhancement.

**Comment by q66** [comment]
it's not meant to be reused, the sole purpose of the variable is for testing (so that failed bootstraps can be restarted)

**Comment by yopito** [comment]
"reuse" is probably not the right term, sorry. I mean be able to fully choose BOOTSTRAP_ROOT, it's more convinient sometimes (especially on boostrap-fail-bootstrap-fail-... sequences)

**Pull request merged**
