### PR TITLE
user/terraform: new package

### PR DESCRIPTION
**Pull request by dmdutra**

### CODE REVIEW

**Comment by q66** [comment]
what's the point of having both terraform and opentofu

**Comment by dmdutra** [comment]
> what's the point of having both terraform and opentofu

Are different projects maintain by different organizations.  Many people uses Terraform instead of OpenTofu.

**Comment by q66** [comment]
that doesn't answer anything

one is literally a fork of the other and one is non-free, so unless there is something meaningful the non-free offers over the free one, i don't see the point in including it

**Comment by dmdutra** [comment]
> that doesn't answer anything
> 
> one is literally a fork of the other and one is non-free, so unless there is something meaningful the non-free offers over the free one, i don't see the point in including it

It's ok for me. I added Terraform just as an alternative to Opentofu. Terraform has more usage than opentofu. But, I will close this PR :)

**Pull request closed without merging**
