### PR TITLE
contrib/nyacme: fix checksum

### PR DESCRIPTION
**Pull request by z-erica**

### CODE REVIEW

**Comment by triallax** [comment]
was this a retag or

**Comment by triallax** [comment]
makes sense, knowing ptrc i wouldn't expect a retag anyway :D

**Comment by nekopsykose** [comment]
is the same forgejo version, just moved from an x86_64 host on alpine to aarch64 on chimera

it doesn't use system zlib or something for zlib-ng so might just be architecture-nondeterministic too in the go compression library or something

**Comment by nekopsykose** [comment]
though rather than confirming 'the files are the same' you should see the actual byte diff

**Comment by nekopsykose** [comment]
ok looked into it- the cached tarballs are gone (obviously), forgejo generates new ones with `git archive` which itself does use system zlib, so zlib-ng has diff checksums (expected)

**Pull request merged**
