### PR TITLE
cbuild stage0: need also xz and patch

### PR DESCRIPTION
**Pull request by yopito**
if not using `bootstrap.sh`.

### CODE REVIEW

**Comment by q66** [comment]
what do you need xz for?

**Comment by yopito** [comment]
xz is needed to extract kernel headers tarball

**Comment by q66** [comment]
i don't see why it would be, during bootstrap the distfiles are all extracted with python's builtin functionality

**Comment by yopito** [comment]
you're right. xz is uneeded anymore. Has changed since last week ;)

**Pull request closed without merging**
