### PR TITLE
main/power-profiles-daemon: update to 0.20

### PR DESCRIPTION
**Pull request by mhmdanas**
cc @valpackett

### CODE REVIEW

**Comment by valpackett** [comment]
Looks good. Any particular reason to use the fd notification over dbus readiness?

**Comment by nekopsykose** [comment]
there is no dbus readiness if you mean waiting for the dbus name to come up. you would need a wrapper like https://github.com/chimera-linux/dbus-wait-for

**Comment by valpackett** [comment]
oh, I thought we built that into dinit itself lol

**Comment by nekopsykose** [comment]
well, once q66 adds that it becomes easy to just add it to command=, i forgot what his plans were :)

**Pull request merged**
