### PR TITLE
user/rspamd: update to 3.9.0

### PR DESCRIPTION
**Pull request by a16bitsysop**
* https://github.com/rspamd/rspamd/releases/tag/3.9.0

### CODE REVIEW

**Comment by a16bitsysop** [comment]
the tests past on alpine:
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/1452333#L2546

**Comment by nekopsykose** [comment]
the check that fails is `CHECK(fstr->len == 26);` because it expectes the zlib buffer to be precisely 26 but zlib-ng specifically allocates more intentionally so the buffer is not 26

**Comment by a16bitsysop** [comment]
ah okay, maybe should be reported upstream then

**Comment by nekopsykose** [comment]
it doesn't affect anything at runtime so just skipping the test is fine

**Pull request merged**
