### PR TITLE
main/imagemagick: update to 7.1.1.21

### PR DESCRIPTION
**Pull request by nekopsykose**
https://github.com/ImageMagick/ImageMagick/releases/tag/7.1.1-21

### CODE REVIEW

**Comment by q66** [comment]
please update the update-check to skip the weird version

**Comment by nekopsykose** [comment]
yeah, just forgot how to make it take `7.*` so it skips all the dual-numerical ones (they keep adding e.g. 77,78,79, ..., so will have to keep skipping those)

**Comment by q66** [comment]
just extend the existing `6*` ignore like `[67]*`

**Comment by nekopsykose** [comment]
that ignores all the actual 7.xyz versions too

**Comment by q66** [comment]
`[67][0-9]` then

**Pull request merged**
