### PR TITLE
main/sane-backends: disable lto

### PR DESCRIPTION
**Pull request by jimipj**
LTO causes segfaults and USB scanner detection issues.

### CODE REVIEW

**Comment by nekopsykose** [comment]
do you have a backtrace?

**Comment by nekopsykose** [comment]
you also have to bump the pkgrel for this to do anything

**Comment by jimipj** [comment]
Oops, it's bumped now.

By USB scanner detection issues, I mean that the scanner isn't automatically
detected. However, if I specify a device, I can run a test or a scan. Both
still result in a segfault at the end.

After comparing logs, I think the detection issue comes from the check_present
function not being called (getting optimized out?). It's defined in
backend/genesys/genesys.cpp at line 5034.

Backtrace from running a test:
```
* thread #1, name = 'scanimage', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x40)
  * frame #0: 0x00007fffef5eeaff libusb-1.0.so.0`libusb_reset_device + 47
    frame #1: 0x00007fffee9eaef6 libsane-genesys.so.1`genesys::UsbDevice::reset() [inlined] sanei_usb_reset(dn=<unavailable>) at sanei_usb.c:3180:9
    frame #2: 0x00007fffee9eaedd libsane-genesys.so.1`genesys::UsbDevice::reset(this=0x00007fffeeb002a0) at usb_device.cpp:65:5
    frame #3: 0x00007fffee94226f libsane-genesys.so.1`genesys::sane_close_impl(void*) [inlined] genesys::sane_close_impl(void*)::$_3::operator()(this=<unavailable>) const at genesys.cpp:5558:76
    frame #4: 0x00007fffee942258 libsane-genesys.so.1`genesys::sane_close_impl(void*) [inlined] void genesys::catch_all_exceptions<genesys::sane_close_impl(void*)::$_3>(func=<unavailable>, function=<unavailable>) at error.h:177:9
    frame #5: 0x00007fffee942258 libsane-genesys.so.1`genesys::sane_close_impl(handle=0x00007fffed602040) at genesys.cpp:5558:5
    frame #6: 0x00007fffee9427b6 libsane-genesys.so.1`::sane_genesys_close(SANE_Handle) [inlined] sane_genesys_close::$_0::operator()(this=<unavailable>) const at genesys.cpp:5571:9
    frame #7: 0x00007fffee9427b0 libsane-genesys.so.1`::sane_genesys_close(SANE_Handle) [inlined] void genesys::catch_all_exceptions<sane_genesys_close::$_0>(func=<unavailable>, function=<unavailable>) at error.h:177:9
    frame #8: 0x00007fffee9427b0 libsane-genesys.so.1`sane_genesys_close(handle=<unavailable>) at genesys.cpp:5569:5
    frame #9: 0x00007fffef9cc204 libsane.so.1`sane_close + 36
    frame #10: 0x000055555555cd14 scanimage`scanimage_exit(status=0) at scanimage.c:1993:7
    frame #11: 0x000055555555c740 scanimage`main(argc=<unavailable>, argv=<unavailable>) at scanimage.c:2971:3
```

**Comment by nekopsykose** [comment]
nothing that seems obvious to me off the bat so let's just make it not broken for now :)

**Pull request merged**
