### PR TITLE
contributing: commit title stuff

### PR DESCRIPTION
**Pull request by nekopsykose**

### CODE REVIEW

**Comment by nekopsykose** [comment]
mostly i just find the new package version supremely pointless, so we could just get rid of it

the second change is just writing down what we do already

**Comment by q66** [comment]
sure

can you change `bsdutils` to some actually relevant (alternatively: generic) example while at it

**Comment by nekopsykose** [comment]
i hope coolproject is generic enough

**Comment by q66** [comment]
yup, perfect

**Pull request merged**
