### PR TITLE
contrib/qt6-* : enable check and some minor fixes

### PR DESCRIPTION
**Pull request by yopito**
some initial work on testing for qt6 packages, probably too verbose and not enough accurate ?
non-check changes on `contrib/qt6-qtbase` should be reorganized separately, ie mode dedicated commits ?

### CODE REVIEW

**Comment by JamiKettunen** [comment]
There's also at least this currently:
```
$ apk info -L qt6-qtbase
qt6-qtbase-6.5.0-r0 contains:
usr/lib/objects-None/moctestplugin_resources_1/.rcc/qrc_qmake_plugin_resource.cpp.o
```

**Comment by nekopsykose** [comment]
the ones with `Could not launch app` you probably have to make a fake screen wrapper for (like xvfb-run does, but maybe someone made one for wayland)

should probably also put `CTEST_OUTPUT_ON_FAILURE` into the build_style because you always want that for ctest testing (and also perhaps `CTEST_PARALLEL_LEVEL`)

**Comment by yopito** [comment]
> There's also at least this currently:
> 
> ```
> $ apk info -L qt6-qtbase
> qt6-qtbase-6.5.0-r0 contains:
> usr/lib/objects-None/moctestplugin_resources_1/.rcc/qrc_qmake_plugin_resource.cpp.o
> ```
you mean remove it too ?

> the ones with `Could not launch app` you probably have to make a fake screen wrapper for (like xvfb-run does, but maybe someone made one for wayland)

I don't think so: `QT_QPA_PLATFORM` (that is `offscreen`) is a fake screen wrapper.
Most of these kind of tests want something that is not yet installed (like `qmlscene`) ...
 
> should probably also put `CTEST_OUTPUT_ON_FAILURE` into the build_style because you always want that for ctest testing (and also perhaps `CTEST_PARALLEL_LEVEL`)

Yes, it would be convenient.

**Comment by nekopsykose** [comment]
> I don't think so: QT_QPA_PLATFORM (that is offscreen) is a fake screen wrapper.
Most of these kind of tests want something that is not yet installed (like qmlscene) ...  

ah, good point. didn't know about offscreen :)

**Comment by q66** [comment]
i will get this in manually with 6.5.1 update and reformatting

**Pull request closed without merging**
