### PR TITLE
main/libcxxabi-cross: fix build, remove unused cmake flags

### PR DESCRIPTION
**Pull request by yopito**

### CODE REVIEW

**Comment by yopito** [comment]
for the record, here the build output without this patch:

```
$ ./cbuild pkg main/libcxxabi-cross

OK: 194 distinct packages available
=> cbuild: updating software in /build/chimera/bldroot container...
=> cbuild: removing autodeps...
OK: 395 MiB in 58 packages
=> libcxxabi-cross-13.0.0-r0: building [cmake] for x86_64...
   [host] cmake: found (3.21.1-r0)
   [host] python: found (3.10.0-r0)
   [target] libunwind-cross: found (13.0.0-r0)
   [runtime] libunwind-cross>=0: found (13.0.0-r0)
   [runtime] libcxxabi-cross-aarch64=13.0.0-r0: subpackage (ignored)
   [runtime] libcxxabi-cross-ppc64le=13.0.0-r0: subpackage (ignored)
   [runtime] libcxxabi-cross-ppc64=13.0.0-r0: subpackage (ignored)
   [runtime] libcxxabi-cross-riscv64=13.0.0-r0: subpackage (ignored)
   [runtime] libunwind-cross-aarch64>=0: found (13.0.0-r0)
   [runtime] libunwind-cross-ppc64le>=0: found (13.0.0-r0)
   [runtime] libunwind-cross-ppc64>=0: found (13.0.0-r0)
   [runtime] libunwind-cross-riscv64>=0: found (13.0.0-r0)
=> libcxxabi-cross-13.0.0-r0: installing host dependencies: cmake, python
=> libcxxabi-cross-13.0.0-r0: installing target dependencies: libunwind-cross
=> libcxxabi-cross-13.0.0-r0: running do_fetch hook: 00_sources...
=> libcxxabi-cross-13.0.0-r0: running do_extract hook: 00_sources...
=> libcxxabi-cross-13.0.0-r0: running init_patch hook: 00_env_pkg_config...
=> libcxxabi-cross-13.0.0-r0: running do_patch hook: 00_patches...
=> libcxxabi-cross-13.0.0-r0: running pre_configure hook: 02_script_wrapper...
=> libcxxabi-cross-13.0.0-r0: running do_configure...
-- The CXX compiler identification is Clang 13.0.0
-- The C compiler identification is Clang 13.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring for standalone build.
-- Linker detection: LLD
-- Found Python3: /usr/bin/python3.10 (found version "3.10.0") found components: Interpreter 
CMake Error at CMakeLists.txt:164 (message):
  LIBCXXABI_LIBCXX_INCLUDES= is not a valid directory.  Please provide the
  path to where the libc++ headers have been installed.


-- Configuring incomplete, errors occurred!
See also "/builddir/libcxxabi-cross-13.0.0/build-aarch64/CMakeFiles/CMakeOutput.log".
=> A failure has occured!
Traceback (most recent call last):
  File "/home/yopito/chimera/cports.git/src/runner.py", line 875, in fire
    case "build" | "check" | "install" | "pkg": do_pkg(cmd)
  File "/home/yopito/chimera/cports.git/src/runner.py", line 806, in do_pkg
    build.build(
  File "/home/yopito/chimera/cports.git/src/cbuild/core/build.py", line 80, in build
    configure.invoke(pkg, step)
  File "/home/yopito/chimera/cports.git/src/cbuild/step/configure.py", line 15, in invoke
    pkg.run_step("configure", optional = True)
  File "/home/yopito/chimera/cports.git/src/cbuild/core/template.py", line 990, in run_step
    if not run_pkg_func(self, "do_" + stepn) and not optional:
  File "/home/yopito/chimera/cports.git/src/cbuild/core/template.py", line 162, in run_pkg_func
    func(pkg)
  File "/home/yopito/chimera/cports.git/main/libcxxabi-cross/template.py", line 51, in do_configure
    cmake.configure(self, self.cmake_dir, f"build-{an}", [
  File "/home/yopito/chimera/cports.git/src/cbuild/util/cmake.py", line 80, in configure
    pkg.do(
  File "/home/yopito/chimera/cports.git/src/cbuild/core/template.py", line 968, in do
    return chroot.enter(
  File "/home/yopito/chimera/cports.git/src/cbuild/core/chroot.py", line 396, in enter
    return subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bwrap', '--unshare-all', '--hostname', 'cbuild', '--ro-bind', PosixPath('/build/chimera/bldroot'), '/', '--bind', PosixPath('/build/chimera/bldroot/builddir'), '/builddir', '--ro-bind', PosixPath('/build/chimera/bldroot/destdir'), '/destdir', '--ro-bind', PosixPath('/build/chimera/sources'), '/sources', '--dev', '/dev', '--proc', '/proc', '--tmpfs', '/tmp', '--tmpfs', '/var/tmp', '--new-session', '--die-with-parent', '--bind', PosixPath('/build/chimera/ccache'), '/ccache', '--uid', '1337', '--gid', '1337', '--chdir', PosixPath('/builddir/libcxxabi-cross-13.0.0/build-aarch64'), 'cmake', '-DCMAKE_INSTALL_PREFIX=/usr', '-DCMAKE_BUILD_TYPE=None', '-DCMAKE_INSTALL_LIBDIR=lib', '-DCMAKE_INSTALL_SBINDIR=bin', '-DCMAKE_BUILD_TYPE=Release', '-Wno-dev', '-DCMAKE_C_COMPILER=/usr/bin/clang', '-DCMAKE_CXX_COMPILER=/usr/bin/clang++', '-DCMAKE_AR=/usr/bin/llvm-ar', '-DCMAKE_NM=/usr/bin/llvm-nm', '-DCMAKE_RANLIB=/usr/bin/llvm-ranlib', '-DLLVM_CONFIG_PATH=/usr/bin/llvm-config', '-DLIBCXXABI_USE_LLVM_UNWINDER=YES', '-DLIBCXXABI_USE_COMPILER_RT=YES', '-DCMAKE_SYSROOT=/usr/aarch64-linux-musl', '-DCMAKE_ASM_COMPILER_TARGET=aarch64-linux-musl', '-DCMAKE_CXX_COMPILER_TARGET=aarch64-linux-musl', '-DCMAKE_C_COMPILER_TARGET=aarch64-linux-musl', PosixPath('/builddir/libcxxabi-cross-13.0.0/libcxxabi')]' returned non-zero exit status 1.
```

**Comment by yopito** [comment]
next: `clang-rt-cross` is also broken. Will try to give a look and enhance this PR or create a dedicated one if prefered.

**Comment by q66** [comment]
thanks for reporting, i prefer to keep the unused flags in since they don't hurt anything and are correct (in case libcxxabi adds some asm targets, etc)

**Comment by q66** [comment]
it seems i also fixed clang-rt-cross with my missing patch import, built fine here

**Pull request closed without merging**
