### PR TITLE
main/clang-rt-crt-cross: add missing gmake dependency

### PR DESCRIPTION
**Pull request by catgirlconspiracy**
not sure how that would end up missing? a transitive dependency that got changed?

### CODE REVIEW

**Comment by q66** [comment]
hm? it's not needed

**Comment by q66** [comment]
ah, no, it is needed for the musl headers setup

@nekopsykose got a bit overeager dropping stuff in 1565ff08114814c9ff8a27d6fac72ccbe1a0c862 and probably did not notice

**Comment by q66** [comment]
(for next time it is not necessary to increase pkgrel for this kind of changes, it only occured to me now)

**Comment by catgirlconspiracy** [comment]
so i guess that's why it didn't get rebuilt?

**Comment by q66** [comment]
it never needed rebuilding, it's just a build tool switch

**Pull request merged**
