### PR TITLE
nuke typing_extensions from 2 packages

### PR DESCRIPTION
**Pull request by nekopsykose**
annoyin ass compat packages

### CODE REVIEW

**Comment by q66** [comment]
y tho

**Comment by nekopsykose** [comment]
useless empty dep

that said twisted is p big anyway and setuptools_scm is just fixed in next version anyway

**Comment by q66** [comment]
i'll merge this if you also remove the `python-typing_extensions` package since it's now a leaf

**Comment by nekopsykose** [comment]
it should be kept because there are things that would actually use it beyond backported types in the future (mypy, ..)

**Comment by q66** [comment]
can't we just nuke typing_extensions from these individually

doesn't seem super hard to do

**Comment by nekopsykose** [comment]
that wouldn't make sense in every case

**Pull request closed without merging**
