### PR TITLE
cbuild: need some str() convertion back

### PR DESCRIPTION
**Pull request by yopito**
partial revert of 9ce7f5d959eabc6f436bb72c92370318eb076690

### CODE REVIEW

**Comment by q66** [comment]
what for?

**Comment by yopito** [comment]
fix crash like:
```
$ ./cbuild.py -a ppc64 pkg ccache
WARNING: Ignoring /binpkgs/nonfree: No such file or directory
WARNING: Ignoring /binpkgs/debug: No such file or directory
OK: 181 distinct packages available
=> cbuild: updating software in /build/chimera/masterdir masterdir...
=> cbuild: removing autodeps...
WARNING: Ignoring /binpkgs/nonfree: No such file or directory
WARNING: Ignoring /binpkgs/debug: No such file or directory
OK: 383 MiB in 69 packages
=> cbuild: removing autodeps...
=> ccache-4.2.1-r0: updating virtual provider for ppc64...
=> ccache-4.2.1-r0: removing autocrossdeps for ppc64...
=> ccache-4.2.1-r0: building [cmake] for ppc64...
   [host] cmake: found (3.20.3-r0)
   [host] ninja: found (1.10.2-r0)
   [host] perl: found (5.32.1-r0)
   [target] libzstd-devel: found (1.5.0-r0)
   [target] zlib-devel: found (1.2.11-r0)
=> ccache-4.2.1-r0: installing host dependencies: cmake, ninja, perl
=> ccache-4.2.1-r0: installing target dependencies: libzstd-devel, zlib-devel
=> ccache-4.2.1-r0: running init_patch hook: 00_env_pkg_config...
=> ccache-4.2.1-r0: running pre_configure hook: 02_script_wrapper...
=> ccache-4.2.1-r0: running do_configure...
=> A failure has occured!
Traceback (most recent call last):
  File "/home/yopito/chimera/cports.git/./cbuild.py", line 390, in <module>
    ({
  File "/home/yopito/chimera/cports.git/./cbuild.py", line 381, in do_pkg
    build.build(tgt, rp, {}, opt_signkey)
  File "/home/yopito/chimera/cports.git/cbuild/core/build.py", line 42, in build
    configure.invoke(pkg, step)
  File "/home/yopito/chimera/cports.git/cbuild/step/configure.py", line 15, in invoke
    pkg.run_step("configure", optional = True)
  File "/home/yopito/chimera/cports.git/cbuild/core/template.py", line 649, in run_step
    if not run_pkg_func(self, "do_" + stepn) and not optional:
  File "/home/yopito/chimera/cports.git/cbuild/core/template.py", line 159, in run_pkg_func
    func(pkg)
  File "/home/yopito/chimera/cports.git/cbuild/build_style/cmake.py", line 4, in do_configure
    cmake.configure(self, self.cmake_dir)
  File "/home/yopito/chimera/cports.git/cbuild/util/cmake.py", line 73, in configure
    pkg.do(
  File "/home/yopito/chimera/cports.git/cbuild/core/template.py", line 585, in do
    "CFLAGS": self.get_cflags(shell = True),
  File "/home/yopito/chimera/cports.git/cbuild/core/template.py", line 665, in get_cflags
    return target.get_cflags(
  File "/home/yopito/chimera/cports.git/cbuild/core/profile.py", line 188, in get_cflags
    return shlex.join(ret)
  File "/usr/lib/python3.9/shlex.py", line 320, in join
    return ' '.join(quote(arg) for arg in split_command)
  File "/usr/lib/python3.9/shlex.py", line 320, in <genexpr>
    return ' '.join(quote(arg) for arg in split_command)
  File "/usr/lib/python3.9/shlex.py", line 329, in quote
    if _find_unsafe(s) is None:
TypeError: expected string or bytes-like object
```

**Comment by q66** [comment]
better fix: 6bfb4d1abfa92a25531434037d6b3da4e76f5ead

this is not really a fix since the assumption is that path-like objects may be present in user-defined `CFLAGS` and so on as well, which come from the outside

**Comment by yopito** [comment]
clever fix, indeed

**Pull request closed without merging**
