### PR TITLE
user/motif: new package (2.3.8)

### PR DESCRIPTION
**Pull request by mikoxyz**
threw this in user/ due to how cursed motif is

### CODE REVIEW

**Comment by q66** [comment]
do you have something actually reasonable to use this with or is this just a meme

**Comment by mikoxyz** [comment]
> do you have something actually reasonable to use this with or is this just a meme

is cde reasonable?

**Comment by q66** [comment]
if somebody's unironically going to use it

**Comment by Alasofia** [comment]
Actively trying to build Motif software on Chimera and this would be *lovely*.
XFile my beloved!

Also looking into a commit for the [2.4.1 modernization update.](https://github.com/dimmus/motif)

**Pull request closed without merging**
