### PR TITLE
contrib/libaacs: enable cfi

### PR DESCRIPTION
**Pull request by mikoxyz**

### CODE REVIEW

**Comment by nekopsykose** [comment]
you could replace the patch with a regular file in files/

but i dunno how much i like this kind of thing

**Comment by mikoxyz** [comment]
> you could replace the patch with a regular file in files/
> 
> but i dunno how much i like this kind of thing

can we even copy files into the src dir?

**Comment by yanchan09** [comment]
honestly i feel like cbuild should have a better support e.g. helper functions for cfi (and ubsan?) exclusions in the first place

**Comment by q66** [comment]
these shouldn't be exclusions but a patch

**Comment by nekopsykose** [comment]
is this still a draft

**Comment by mikoxyz** [comment]
please take a look at this again

**Pull request merged**
