### PR TITLE
main/libxml2: update to 2.11.5

### PR DESCRIPTION
**Pull request by nekopsykose**

### CODE REVIEW

**Comment by nekopsykose** [comment]
not sure if it was intentional or not to not update this ever since adding it and if i missed some secret reason, aside from the update-check not functioning

**Comment by q66** [comment]
the only reason was uniquely broken update-check (returning versions i.e. not complaining but not returning current versions) so it went under the radar

**Comment by q66** [comment]
is there any reason for the subpackage shuffle

**Comment by nekopsykose** [comment]
devel gets the remainder of usr/share/doc/libxml2 after python gets libxml2/python (before they were separate dirs)

**Pull request merged**
