### PR TITLE
main/polkit: update to 124

### PR DESCRIPTION
**Pull request by triallax**

### CODE REVIEW

**Comment by q66** [comment]
please rebase

**Comment by triallax** [comment]
rebased

**Comment by triallax** [comment]
just realised that it seems like everything else installs pam rules to /etc/pam.d, should i do that here too?

**Comment by q66** [comment]
i'm thinking maybe i should have all distro pam go in /usr instead, but still thinking about it

**Comment by q66** [comment]
doesn't work (pkexec doesn't work, device automount doesn't work, etc)

**Pull request closed without merging**
