### PR TITLE
main/zlib-ng-compat: new package (2.1.7)

### PR DESCRIPTION
**Pull request by q66**
We could give this a try. Let's have people test it

### CODE REVIEW

**Comment by nekopsykose** [comment]
one thing i notice when testing small stuff like this is that if you have -dbg of the old thing (i.e. i had `zlib-dbg` in world) it won't upgrade and you have to go remove it first. maybe we should make -dbg not actually depend on the base package?

**Comment by nekopsykose** [comment]
comparison on a tiny font  

```
# zlib-ng:
$ l
.rw-r--r-- 485k demon demon 1 second FullGreek-DejaVu118x64.psf
.rw-r--r-- 150k demon demon 1 second FullGreek-DejaVu118x64.psf.gz
$ hyperfine -N --output /dev/null 'gzip -d -c FullGreek-DejaVu118x64.psf.gz'
Benchmark 1: gzip -d -c FullGreek-DejaVu118x64.psf.gz
  Time (mean ± σ):     687.1 µs ±  53.5 µs    [User: 456.2 µs, System: 190.3 µs]
  Range (min … max):   559.8 µs … 961.8 µs    3119 runs
 
$ hyperfine -N --output /dev/null 'gzip -9n -c FullGreek-DejaVu118x64.psf'
Benchmark 1: gzip -9n -c FullGreek-DejaVu118x64.psf
  Time (mean ± σ):      19.5 ms ±   0.7 ms    [User: 19.1 ms, System: 0.4 ms]
  Range (min … max):    18.5 ms …  21.3 ms    152 runs


# original zlib:


$ hyperfine -N --output /dev/null 'gzip -d -c FullGreek-DejaVu118x64.psf.gz'
Benchmark 1: gzip -d -c FullGreek-DejaVu118x64.psf.gz
  Time (mean ± σ):     998.9 µs ±  71.6 µs    [User: 657.9 µs, System: 299.8 µs]
  Range (min … max):   859.5 µs … 1405.6 µs    2413 runs
 
$ hyperfine -N --output /dev/null 'gzip -9n -c FullGreek-DejaVu118x64.psf'
Benchmark 1: gzip -9n -c FullGreek-DejaVu118x64.psf
  Time (mean ± σ):      44.8 ms ±   0.8 ms    [User: 44.3 ms, System: 0.4 ms]
  Range (min … max):    43.8 ms …  47.6 ms    65 runs
```

and something bigger

```
# zlib-ng:
$ l
.rw-r--r-- 330M demon demon now        VTK-9.3.0.tar
.rw-r--r-- 100M demon demon 15 seconds VTK-9.3.0.tar.gz
$ hyperfine -N --output /dev/null 'gzip -d -c VTK-9.3.0.tar.gz'
Benchmark 1: gzip -d -c VTK-9.3.0.tar.gz
  Time (mean ± σ):     343.3 ms ±   1.1 ms    [User: 336.8 ms, System: 6.2 ms]
  Range (min … max):   341.7 ms … 345.0 ms    10 runs
 
$ hyperfine -N --output /dev/null 'gzip -9n -c VTK-9.3.0.tar'
Benchmark 1: gzip -9n -c VTK-9.3.0.tar
  Time (mean ± σ):      6.737 s ±  0.032 s    [User: 6.708 s, System: 0.026 s]
  Range (min … max):    6.714 s …  6.799 s    10 runs


# original zlib:

$ hyperfine -N --output /dev/null 'gzip -d -c VTK-9.3.0.tar.gz'
Benchmark 1: gzip -d -c VTK-9.3.0.tar.gz
  Time (mean ± σ):     541.1 ms ±  10.2 ms    [User: 530.4 ms, System: 10.4 ms]
  Range (min … max):   533.5 ms … 561.8 ms    10 runs
 
$ hyperfine -N --output /dev/null 'gzip -9n -c VTK-9.3.0.tar'
Benchmark 1: gzip -9n -c VTK-9.3.0.tar
  Time (mean ± σ):     18.643 s ±  0.019 s    [User: 18.620 s, System: 0.016 s]
  Range (min … max):   18.609 s … 18.678 s    10 runs
```

seems compression is 2-3x faster for the same thing, and decompression like 40%, on x86_64 anyway. seems nice.

small note is that (obviously) the output is not bit-for-bit identical:  

```
$ sha1sum original-zlib-VTK-9.3.0.tar.gz zlib-ng-VTK-9.3.0.tar.gz 
370eee71f2e6868e7f3e66b264da945abdcbd54f  original-zlib-VTK-9.3.0.tar.gz
2afe9bdb947c70d90939b983314be7b15b5149f8  zlib-ng-VTK-9.3.0.tar.gz
```

this does break a testsuite or two that expects a certain golden checksum in a compression test that was generated with original zlib. but the only thing i heard of so far that this breaks is the ffmpeg testsuite that we don't run anyway

**Comment by q66** [comment]
> one thing i notice when testing small stuff like this is that if you have -dbg of the old thing (i.e. i had `zlib-dbg` in world) it won't upgrade and you have to go remove it first. maybe we should make -dbg not actually depend on the base package?

i'll just add zlib-dbg to provides of the zlib-ng-compat as a workaround if i end up merging it

**Comment by nekopsykose** [comment]
that seems like more of a hack hehe

**Pull request closed without merging**
