### PR TITLE
main/libsoup: update to 3.5.1

### PR DESCRIPTION
**Pull request by triallax**

### CODE REVIEW

**Comment by nekopsykose** [comment]
i wasnt sure if this is 'beta' or not, did they stop doing oddvers

**Comment by triallax** [comment]
good point, i'm not quite sure so i guess i'll ask in the gnome matrix room real quick

**Comment by q66** [comment]
https://gitlab.gnome.org/GNOME/libsoup/-/tags

>3.5.1 (dev)

**Comment by triallax** [comment]
guess we'll want to ignore oddvers in update.py then?

**Pull request closed without merging**
